name: PDF Compilation

on:
  push:
    branches: [ master ]


jobs:
  compile_md:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4

    - name: I4.0 Concept PDF Compilation
      run: |
        npm install -g markdown-pdf
        markdown-pdf -f A4 -s assets/css/main.css CertifiedByGs1-I40.md

    - name: Save PDF
      uses: actions/upload-artifact@v4
      with:
        name: Certified-by-GS1-Concepts
        path: CertifiedByGs1-I40.pdf

  compile_adoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        doc: ["CertifiedByGs1-Trust", "CertifiedByGs1-PKI-Demo", "CertifiedByGs1-OnePager", "white-paper"]
        
    steps:
    - uses: actions/checkout@v4

    - name: Trust Model PDF Compilation
      uses: docker://asciidoctor/docker-asciidoctor:latest
      with:
        entrypoint: asciidoctor-pdf
        args: -a icons=font -a source-highlighter=coderay ${{ matrix.doc }}.adoc

    - name: Save PDF
      uses: actions/upload-artifact@v4
      with:
        name: Certified-by-GS1-Concepts
        path: ${{ matrix.doc }}.pdf

