on:
  release:
    types:
      - created

name: Release PDFs

jobs:
  buildI40:
    name: compile and upload markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Compile I 4.0 Concept PDF
        run: |
          npm install -g markdown-pdf
          markdown-pdf -f A4 -s assets/css/main.css -m '{"html":true, "breaks":false}' CertifiedByGs1-I40.md
          ls -lah ./CertifiedByGs1-I40.pdf

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./CertifiedByGs1-I40.pdf
          asset_name: CertifiedByGs1-I40.pdf
          asset_content_type: application/pdf
  buildTrust:
    name: compile and upload adocs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        doc: ["CertifiedByGs1-Trust", "CertifiedByGs1-PKI-Demo", "CertifiedByGs1-OnePager", "white-paper"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Trust Model PDF Compilation
        uses: docker://asciidoctor/docker-asciidoctor:latest
        with:
          entrypoint: asciidoctor-pdf
          args: -a icons=font -a source-highlighter=coderay ${{ matrix.doc }}.adoc

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.doc }}.pdf
          asset_name: ${{ matrix.doc }}.pdf
          asset_content_type: application/pdf

